services:
  tomee:
    image: tomee:jre21-webprofile
    container_name: tomee
    ports:
      - "8989:8080"
    volumes:
      - ./target/firstweb:/usr/local/tomee/webapps
    depends_on:
      - db

  db:
    image: mysql:8.0.34
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
      MYSQL_USER: cristian
      MYSQL_PASSWORD: secret
    ports:
      - "3366:3306"
    volumes:
      - db_data_server:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  db_data_server: